-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 22:02:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CoffeyDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CoffeyDB` ;

-- -----------------------------------------------------
-- Schema CoffeyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoffeyDB` DEFAULT CHARACTER SET utf8 ;
USE `CoffeyDB` ;

-- -----------------------------------------------------
-- Table `sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint` (
  `sprint_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sprint_name` MEDIUMTEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `tickets` JSON NULL,
  PRIMARY KEY (`sprint_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `sprint_id_UNIQUE` ON `sprint` (`sprint_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket` (
  `ticket_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignee_id` INT NULL,
  `reporter_id` INT NULL,
  `implementer_id` INT NULL,
  `title` MEDIUMTEXT NOT NULL,
  `create_date` DATETIME NOT NULL,
  `update_date` DATETIME NOT NULL,
  `component` TINYINT NOT NULL,
  `priority` TINYINT NULL,
  `status` TINYINT NOT NULL,
  `other_data` JSON NULL,
  `sprint_id` SMALLINT NULL,
  PRIMARY KEY (`ticket_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ticket_id_UNIQUE` ON `ticket` (`ticket_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(64) NOT NULL,
  `user_role` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `users` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
